// Reconstructed from the original site bundle. Logic is kept behaviorally equivalent.
export function init() {
  let i=document.querySelectorAll(`input[name="service_type"]`),a=document.getElementById(`field-guest`),o=document.getElementById(`field-destination`);
document.querySelectorAll(`#hero-submit-btn span.block`),i.length>0&&a&&o&&i.forEach(e=>{e.addEventListener(`change`,e=>{e.target.value===`transports`?(a.classList.replace(`block`,`hidden`),o.classList.replace(`hidden`,`block`)):(o.classList.replace(`block`,`hidden`),a.classList.replace(`hidden`,`block`))})});
let s=document.getElementById(`booking-date`);
s&&window.flatpickr(s,{dateFormat:`d/m/Y`,minDate:`today`,disableMobile:`true`,onOpen:function(e,t,n){window.innerWidth>=1024&&setTimeout(()=>{let e=n.element.getBoundingClientRect(),t=n.calendarContainer.getBoundingClientRect(),r=e.left-t.width-80;n.calendarContainer.style.left=`window.ScrollTrigger{r+window.scrollX}px`,n.calendarContainer.style.top=`window.ScrollTrigger{e.top+window.scrollY-60}px`,n.calendarContainer.style.right=`auto`,n.calendarContainer.style.bottom=`auto`},0)}});
let c=document.getElementById(`guest-input-container`),l=document.getElementById(`guest-dropdown`),u=document.getElementById(`guest-input`),d=document.getElementById(`btn-guest-apply`);
if(c&&l){let e=parseInt(c.dataset.adults)||2,t=c.dataset.children===void 0?0:parseInt(c.dataset.children),n=document.getElementById(`btn-adult-minus`),r=document.getElementById(`btn-adult-plus`),i=document.getElementById(`adult-count`),a=document.getElementById(`btn-child-minus`),o=document.getElementById(`btn-child-plus`),s=document.getElementById(`child-count`),f=e=>{if(e!==void 0)e?(l.classList.remove(`hidden`),c.setAttribute(`aria-expanded`,`true`)):(l.classList.add(`hidden`),c.setAttribute(`aria-expanded`,`false`));else{let e=l.classList.toggle(`hidden`);c.setAttribute(`aria-expanded`,e?`false`:`true`)}};c.addEventListener(`click`,e=>{e.stopPropagation(),f()}),c.addEventListener(`keydown`,e=>{(e.key===`Enter`||e.key===` `)&&(e.preventDefault(),f())}),document.addEventListener(`click`,e=>{!c.contains(e.target)&&!l.contains(e.target)&&f(!1)});let p=(r=!1)=>{if(i.textContent=e,s.textContent=t,n.disabled=e<=1,a.disabled=t<=0,!r){let n=t>0?`, window.ScrollTrigger{t} Children`:``;u.value=`window.ScrollTrigger{e} Adult${e>1?`s`:``}window.ScrollTrigger{n}`}let o=document.getElementById(`adults-input`),l=document.getElementById(`children-input`);o&&(o.value=e),l&&(l.value=t);let d=c.dataset.prices;if(d)try{let n=JSON.parse(d);if(n.length>0){let r=e+t,i=null;for(let e of n)if(r>=e.min_people&&(e.max_people===null||r<=e.max_people)){i=e;break}if(i||=n.reduce((e,t)=>e.min_people<t.min_people?e:t),i){let n=e*parseFloat(i.adult_price)+t*parseFloat(i.child_price),r=`window.ScrollTrigger`+n.toLocaleString(`en-US`,{minimumFractionDigits:0,maximumFractionDigits:2}),a=document.getElementById(`short-total-price`),o=document.getElementById(`full-total-price`),s=document.getElementById(`total-price-input`);a&&(a.textContent=r),o&&(o.textContent=r),s&&(s.value=n)}}}catch(e){console.error(`Error parsing price data`,e)}};p(!0),n.addEventListener(`click`,()=>{e>1&&(e--,p())}),r.addEventListener(`click`,()=>{e<15&&(e++,p())}),a.addEventListener(`click`,()=>{t>0&&(t--,p())}),o.addEventListener(`click`,()=>{t<10&&(t++,p())}),d.addEventListener(`click`,()=>{l.classList.add(`hidden`)})}
let f=document.getElementById(`transport-service-trigger`),p=document.getElementById(`transport-service-dropdown`),m=document.getElementById(`transport-service-text`),h=document.getElementById(`transport-service-input`),g=document.getElementById(`transport-total-price-input`),_=document.getElementById(`full-total-price`);
}
