import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { SEO } from '../components/SEO/SEO';
import { TourCard, BlogCard, TransportCard } from '../components/Cards/Cards';
import { SectionIntro } from '../components/Hero/Hero';
import { Accordion } from '../components/Accordion/Accordion';
import { tours } from '../data/tours'; import { blogs } from '../data/blogs'; import { transport } from '../data/transport';

export function HomePage(){
 const [service,setService]=useState<'tours'|'transports'>('tours'); const [guests,setGuests]=useState(2);
 return <><SEO title="Bali Bagus Journey - Private Tours & Airport Transfers in Bali" description="Discover Bali with trusted local guides. Book private day tours, airport transfers, and customized Bali travel packages with Bali Bagus Journey." canonical="/"/>
 <section id="home" className="relative min-h-[90dvh] overflow-hidden px-4 pb-12 pt-32 text-white md:px-8 lg:px-12"><img className="gsap-hero-bg absolute inset-0 size-full object-cover" src="/assets/home/hero.webp" alt="Bali"/><div className="gsap-hero-overlay absolute inset-0 bg-gradient-to-b from-black/45 via-black/25 to-black/80"/><div className="relative z-10 mx-auto flex min-h-[70dvh] max-w-7xl items-end"><div className="w-full max-w-4xl"><div className="gsap-hero-badge mb-4 translate-y-8 text-sm font-semibold uppercase tracking-wider opacity-0">Trusted Bali Local Driver</div><h1 className="gsap-hero-title translate-y-16 text-4xl font-semibold leading-tight opacity-0 md:text-6xl lg:text-7xl">Book Trusted Bali Tours & Private Transport with Local Experts</h1><p className="gsap-hero-text mt-6 max-w-2xl translate-y-8 text-base leading-7 text-white/75 opacity-0 md:text-lg">Explore the island with flexible private tours, reliable airport transfers, and local drivers who know Bali.</p>
 <form className="gsap-hero-form mt-8 rounded-3xl bg-white p-4 text-foreground shadow-2xl md:p-5" onSubmit={e=>e.preventDefault()}><div className="grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto] md:items-end"><div className="flex rounded-2xl bg-card p-1"><button type="button" onClick={()=>setService('tours')} className={`flex-1 rounded-xl px-3 py-3 text-sm font-semibold ${service==='tours'?'bg-foreground text-white':''}`}>Tours</button><button type="button" onClick={()=>setService('transports')} className={`flex-1 rounded-xl px-3 py-3 text-sm font-semibold ${service==='transports'?'bg-foreground text-white':''}`}>Transport</button></div><label className="grid gap-1 text-xs font-semibold text-text-label-secondary">Booking date<input type="date" min={new Date().toISOString().slice(0,10)} className="rounded-xl border border-border bg-white px-3 py-3 text-sm text-foreground"/></label>{service==='tours'?<label className="grid gap-1 text-xs font-semibold text-text-label-secondary">Number Of Guest<button type="button" onClick={()=>setGuests(v=>v>=15?1:v+1)} className="rounded-xl border border-border bg-white px-3 py-3 text-left text-sm text-foreground">{guests} Adults</button></label>:<label className="grid gap-1 text-xs font-semibold text-text-label-secondary">Drop Off Point<input className="rounded-xl border border-border bg-white px-3 py-3 text-sm text-foreground" placeholder="Destination"/></label>}<Link to={service==='tours'?'/tours.html':'/transport.html'} className="rounded-full bg-primary px-5 py-3 text-center text-sm font-semibold text-white">Check Availability ↗</Link></div></form></div></div></section>
 <section id="about" className="px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><SectionIntro eyebrow="About Us" title="We help travelers experience Bali with confidence" text="Local knowledge, reliable transportation, and thoughtfully designed private experiences make every day easier."/><div className="grid grid-cols-3 gap-4 border-t border-border pt-6 text-center"><div><b className="block text-3xl">0+</b><span className="text-xs text-text-label-secondary">Happy Travelers</span></div><div><b className="block text-3xl">0.0/5</b><span className="text-xs text-text-label-secondary">Average Rating</span></div><div><b className="block text-3xl">0+</b><span className="text-xs text-text-label-secondary">Years Experience</span></div></div></div><div className="grid grid-cols-2 gap-4"><img src="/assets/home/about/about/about-1 1.webp" className="h-72 w-full rounded-3xl object-cover" alt="Bali travel"/><img src="/assets/home/about/about/about-2.webp" className="mt-12 h-72 w-full rounded-3xl object-cover" alt="Bali journey"/></div></div></section>
 <section id="service" className="bg-card px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Travel Services" title="Travel Services Designed for Every Bali Journey" text="Choose a private experience that matches the way you want to explore Bali."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><Service title="Bali Tours & Activities" text="Private day trips, cultural experiences, island hopping, and nature adventures." href="/tours.html"/><Service title="Private Transport" text="Comfortable vehicles and professional local drivers for airport transfers and sightseeing." href="/transport.html"/><Service title="Airport Transfer" text="Reliable pickup and drop-off service for a smooth arrival and departure." href="/transport.html"/></div></div></section>
 <section id="tour" className="px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Popular Bali Tours" title="Explore Bali's Most Popular Destinations" text="Discover our most-loved Bali tour packages."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tours.slice(0,6).map(t=><TourCard key={t.slug} tour={t}/>)}</div><Link to="/tours.html" className="mx-auto mt-8 flex w-fit rounded-full bg-foreground px-6 py-3 font-semibold text-white">Explore All Tours ↗</Link></div></section>
 <section id="transportation" className="bg-card px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Premium Transport" title="Explore Bali with Professional Local Drivers" text="Comfortable, safe, and flexible transportation for every kind of Bali journey."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{transport.slice(0,3).map(t=><TransportCard key={t.slug} item={t}/>)}</div></div></section>
 <section id="gallery" className="px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Moments Of Travelers" title="A Visual Journey Through Bali's Wonders"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{['bdk2uvvu6stlowu9fhjc.webp','dkuokdg5xh0xpytwno7v.webp','erpcsospbml5v1sl6xzs.webp','sotlfso1va1cge2szlmn.webp'].map(x=><img key={x} src={`/assets/galleries/${x}`} alt="Bali" className="aspect-square rounded-2xl object-cover"/>)}</div><Link to="/gallery.html" className="mt-7 inline-flex rounded-full bg-foreground px-5 py-3 font-semibold text-white">Explore Our Gallery ↗</Link></div></section>
 <section id="why" className="bg-card px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><SectionIntro eyebrow="Why" title="Travel Made Simple" text="Discover why travelers choose us for reliable transportation, local expertise, and flexible private experiences."/><div className="grid gap-4">{['Local expertise','Private & flexible experiences','Professional drivers','Comfortable transportation'].map(x=><div key={x} className="gsap-why-feature scale-90 rounded-2xl bg-white p-5 opacity-0"><b>{x}</b><p className="mt-1 text-sm text-text-label-secondary">Designed around your comfort and itinerary.</p></div>)}</div></div><div className="overflow-hidden rounded-3xl"><img src="/assets/home/why/k3foglqhf8mbbq0ckdf5.webp" alt="Why Bali Bagus Journey" className="size-full object-cover"/></div></div></section>
 <section id="blog" className="px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Blogs & Articles" title="Bali Travel Tips & Destination Guides" text="Find helpful articles about Bali's top attractions, food, culture, and practical travel planning."/><div className="grid gap-5 md:grid-cols-2">{blogs.slice(0,4).map(b=><BlogCard key={b.slug} blog={b}/>)}</div></div></section>
 <section id="faq" className="bg-card px-4 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionIntro eyebrow="FAQs" title="Helpful Answers Before You Book" text="Have another question? Contact us via WhatsApp and we will respond."/><Accordion items={[{question:'Do you offer private tours?',answer:'We focus on authentic, private experiences rather than rushed, crowded tours.'},{question:'Can I book only an airport transfer?',answer:'Not at all. You can book a single day trip or just an airport transfer.'},{question:'When is the best time to visit Bali?',answer:'Bali is great year-round, but the dry season from April to October is ideal for outdoor activities.'},{question:'Can you accommodate special requirements?',answer:'Yes. We strive to make your journey comfortable and can help with accessibility and family needs.'},{question:'Do you operate outside Bali?',answer:'Our core focus is Bali, including day trips to nearby Nusa Penida.'}]}/></div></section>
 </>;
}
function Service({title,text,href}:{title:string;text:string;href:string}){return <Link to={href as any} className="group rounded-3xl bg-white p-6 transition-transform duration-500 hover:-translate-y-1"><div className="mb-10 flex size-12 items-center justify-center rounded-full bg-primary text-white">↗</div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-text-label-secondary">{text}</p><span className="mt-6 inline-flex rounded-full bg-card px-4 py-2 text-sm font-semibold">Explore ↗</span></Link>}
